### ISSUE TITLE
Cannot test. Wrong dimensions

### ISSUE THREAD

**Issue by Scolymus** [tsingqguo/misf#8]
Hi!

Thanks for leaving here your project. Looks amazing! However, I wanted to test it and I got stucked. I downloaded the code and the models. Then, I use one of my images in jpg and after running the dataset I have two files, flist_real.txt and flist_mask.txt which contains:
["test_images\\1.jpg"] and ["test_images\\1_mask.jpg"] respectively. Now I ran the program and I got an error because of the dimensions. Should I have some special dimensions from the begginig? It's strange to see that if I use a png image instead of 6 channels error I got 8 channels...

What am I doing wrong? What version of pytorch and torchvision are you using?

```
Namespace(angle_aug=True, b1=0.5, b2=0.999, blind_est=True, burst_length=1, channel_att=False, color=True, core_bias=False, crop=False, crop_size=256, cudnn_benchmark=True, dataset=1, erode=19, eval_data='./data/face.txt', eval_interval=2, eval_mask='./data/mask_20.txt', eval_sample='./result/eval_sample', eval_sample_interval=1, geometry_aug=False, gpu_ids='0', init_gain=0.02, init_type='xavier', kernel_size=[3], load_name='./result/model/251000_KPN_bs_8_opt.pth', lr_decay=0.9, lr_decay_interval=1, lr_decrease_epoch=20, lr_g=0.0002, mask_threshold=100, mu=0, multi_gpu=False, num_workers=0, rainaug=False, save_mode_interval=1, save_model='./result/model/', scale_max=1, scale_min=1, sep_conv=False, sigma=30, spatial_att=False, test_batch_size=1, test_data='./data/dunhuang.txt', test_mask='./data/dunhuang_mask.txt', test_sample='./result/test_sample', test_sample_interval=1, train_batch_size=1, train_data='./data/face.txt', train_mask='./data/mask_20.txt', train_sample='./result/train_sample', train_sample_interval=1, upMode='bilinear', weight_decay=0)
initialize network with xavier type
Generator is created!
C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torchvision\models\_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\lpips\weights\v0.1\vgg.pth
training:False  mask:6  mask_list:./flist_mask.txt  data_list:./flist_real.txt
test dataset:
Loading InpaintingModel generator...
start testing...

+++++++++++++++
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    main(mode=2)
  File "C:\Users\Scolymus\Desktop\misf\main.py", line 69, in main
    model.test()
  File "C:\Users\Scolymus\Desktop\misf\src\misf.py", line 395, in test
    outputs = self.inpaint_model(images, edges, masks)
  File "C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Scolymus\Desktop\misf\src\models.py", line 278, in forward
    outputs = self.generator(inputs)      # in: [rgb(3) + edge(1)]
  File "C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Scolymus\Desktop\misf\src\networks.py", line 91, in forward
    x = self.encoder0(x) # 64*256*256
  File "C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Scolymus\.conda\envs\py37\lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 4, 7, 7], expected input[1, 6, 4006, 6006] to have 4 channels, but got 6 channels instead
```

**Comment by Scolymus** [comment]
So I changed in line 102 in dataset.py:   

        mask = scipy.misc.imread(self.mask_data[mask_index], mode='L')

when loading the mask. Now it process. Btw, there are a couple of functions already deprecated in newer scipy versions. For example, scipy.misc.imread should be replaced by imageio.imread, while scipy.misc.resize has alternatives with pillow.

Do you have your network trained for higher resolutions? I noticed that if you use a not 256x256 image the network fails.
